CREATE TABLE tabl1 (
  id SERIAL
);

-- behind the scenes
CREATE TABLE table_name (
  id integer NOT NULL DEFAULT nextval('table_name_id_seq')
);
ALTER SEQUENCE table_name_id_seq
OWNED BY table_name.id;


CREATE TABLE IF NOT EXISTS fruits (
  id SERIAL PRIMARY KEY,
    name VARCHAR NOT NULL
);
-- id would have default value
INSERT INTO fruits(name) VALUES ('orange');
-- can be explicit
INSERT INTO fruits(id, name) VALUES (DEFAULT, 'apple');


-- to get sequence name of serial col
pg_get_serial_sequence('table_name', 'column_name');

-- can pass it to currval() to get recent value, generated by sequence
SELECT currval(pg_get_serial_sequence('fruits', 'id'));

-- to show returning id
INSERT INTO fruits(name) VALUES ('banana')
RETURNING id;


